---
# tasks file for roles/network

- name: Set DEFROUTE=No
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DEFROUTE='
    line: DEFROUTE="no"
  notify:
    - restart network

- name: GATEWAY
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
    insertafter: 'NETMASK'
    regexp: '^GATEWAY='
    line: 'GATEWAY=192.168.1.193'
    state: present
  notify:
    - restart network

- name: start network
  systemd:
    name: network
    state: restarted
